-intstyle "ise" -incremental -o "D:/Arquitectura/Componentes/RegisterFile/tb_RegisterFile_isim_beh.exe" -prj "D:/Arquitectura/Componentes/RegisterFile/tb_RegisterFile_beh.prj" "work.tb_RegisterFile" 
